<!-- 2019-02-10
"Add the AWQuality logo to all product pages of the AWQuality category"
https://www.upwork.com/ab/f/contracts/21523399
https://github.com/alleswunder2/core/issues/1 -->
<div class="aw-logo field-tooltip toggle">
	<img
		aria-autoclose="false"
		class="field-tooltip-action action-help"
		data-bind="mageInit: {dropdown:{activeClass: '_active'}}"
		data-toggle="dropdown"
		src='<?= df_asset_url('AllesWunder_Core::i/aw-logo.png') ?>'
		tabindex="0"
	/>
	<div
		class="field-tooltip-content"
		data-target="dropdown"
	><?= __('AW_LOGO_HOVER_TEXT') ?></div>
</div>
<?= df_js('AllesWunder_Core', 'aw-logo') ?>